/*
 * Portfolio data.
 *
 * Every project is a repository owned by github.com/Treppord that was pushed to in the last
 * two years. `visibility` is only the last known state: on page load the site asks GitHub
 * which repos are public and updates badges, filters and source links to match, so flipping
 * a repo to public on GitHub is enough.
 *
 * To add a project, add an entry to `projects` (and optionally its language split to
 * `languages`). Categories without projects are hidden automatically.
 */
window.PORTFOLIO = (() => {
  const categories = [
    { id: "minecraft", label: "Minecraft & Game Mods", sub: "Java · Fabric · NeoForge · Vintage Story", accent: "#4ade80" },
    { id: "engines", label: "Game Engines", sub: "From scratch in C++, Rust & Go", accent: "#fb923c" },
    { id: "games", label: "Games", sub: "C++ · Go · Java · Godot · Python", accent: "#f43f5e" },
    { id: "apps", label: "Apps", sub: "iOS · macOS · Desktop · VS Code", accent: "#e879f9" },
    { id: "web", label: "Websites & Web Apps", sub: "Next.js · React · Vue · Go", accent: "#38bdf8" },
    { id: "api", label: "APIs & Backend", sub: "Go · TypeScript · Supabase · Pulumi", accent: "#a78bfa" },
    { id: "tools", label: "Tools & Generators", sub: "Python · Go", accent: "#facc15" },
    { id: "ai", label: "AI Research", sub: "Rust · Python", accent: "#2dd4bf" },
  ];

  const projects = [
    /* ---------- Minecraft & game mods ---------- */
    {
      repo: "got-mod",
      title: "A Game of Blocks",
      category: "minecraft",
      visibility: "private",
      featured: true,
      description:
        "A Game of Thrones overhaul for Minecraft 1.21.1: kingdoms, religions, troops, quests and blacksmithing, plus a public addon API that other mods build on.",
      tags: ["Fabric", "Mod API"],
      created: "2026-03-28",
      updated: "2026-08-30",
    },
    {
      repo: "swbb",
      title: "SWBB",
      category: "minecraft",
      visibility: "private",
      featured: true,
      description:
        "Multi-loader Star Wars mod for Minecraft 1.21.1 with lightsabers, blasters, stormtrooper armor, Tatooine structures, custom sounds and a web-based schematic viewer.",
      tags: ["Fabric", "Forge", "NeoForge"],
      created: "2026-08-18",
      updated: "2026-09-09",
    },
    {
      repo: "middle-earth-war",
      title: "Middle-earth: War",
      category: "minecraft",
      visibility: "public",
      description:
        "Add-on for the Middle-earth mod: hire soldiers from faction leaders, order them to follow or hold, and organise them into armies. Server-authoritative and datapack-driven.",
      tags: ["Fabric", "Datapacks"],
      created: "2025-08-24",
      updated: "2026-08-31",
    },
    {
      repo: "middle-earth-factions",
      title: "Middle-earth: Factions",
      category: "minecraft",
      visibility: "private",
      description:
        "Faction titles, five server-validated ranks with perks, shared map waypoints and live text placeholders for the Middle-earth mod.",
      tags: ["Fabric", "Placeholder API"],
      created: "2025-08-06",
      updated: "2026-08-02",
    },
    {
      repo: "middle-earth-npc",
      title: "Middle-earth: NPC",
      category: "minecraft",
      visibility: "private",
      description: "Workstation roles and data-driven, server-authoritative NPC shops for the Middle-earth mod.",
      tags: ["Fabric", "Datapacks"],
      created: "2025-08-27",
      updated: "2026-08-02",
    },
    {
      repo: "cobblefight",
      title: "CobbleFight",
      category: "minecraft",
      visibility: "private",
      description:
        "Rated Cobblemon matchmaking for servers: queue up, battle in server-built arenas, then climb the ranks and the rating leaderboard.",
      tags: ["Cobblemon", "NeoForge"],
      created: "2026-08-09",
      updated: "2026-08-09",
    },
    {
      repo: "agob-example-addon",
      title: "AGOB Example Addon",
      category: "minecraft",
      visibility: "public",
      description:
        "A small, copyable addon for A Game of Blocks that shows off its API: a Dothraki kingdom, a custom religion, troops, a quest template, blacksmith recipes and armor.",
      tags: ["Fabric", "Mod API"],
      created: "2026-05-02",
      updated: "2026-05-09",
    },
    {
      repo: "force-mod",
      title: "The Force",
      category: "minecraft",
      visibility: "private",
      description: "Force powers in Minecraft 1.20.2, built on a force-sensitive player API injected with mixins.",
      tags: ["Fabric", "Mixins"],
      created: "2026-03-27",
      updated: "2026-05-17",
    },
    {
      repo: "dune-mod",
      title: "Dune Mod",
      category: "minecraft",
      visibility: "private",
      description: "A Fabric mod inspired by Dune, starting with the Arrakis dimension.",
      tags: ["Fabric"],
      created: "2026-03-26",
      updated: "2026-03-27",
    },
    {
      repo: "city-utils",
      title: "City Utils",
      category: "minecraft",
      visibility: "private",
      description: "Server-side utilities for a city server, starting with an NPC framework.",
      tags: ["Fabric", "Server-side"],
      created: "2026-03-25",
      updated: "2026-03-26",
    },
    {
      repo: "property-mod",
      title: "Property Mod",
      category: "minecraft",
      visibility: "private",
      description: "Server-driven housing and property system that works through vanilla-compatible menus and commands.",
      tags: ["Fabric", "Server-side"],
      created: "2026-03-24",
      updated: "2026-03-26",
    },
    {
      repo: "sweet-greens",
      title: "Sweet Greens",
      category: "minecraft",
      visibility: "private",
      description:
        "Farming and consumables: grow strains, dry and roll them, and compress two dried buds into a hybrid with merged effects.",
      tags: ["Fabric"],
      created: "2026-03-20",
      updated: "2026-03-25",
    },
    {
      repo: "treps-servers",
      title: "Treps Servers Core",
      category: "minecraft",
      visibility: "private",
      description:
        "Server-only core library with events, scheduling and utilities for building gameplay features that need no client mods.",
      tags: ["Fabric", "Server-side"],
      created: "2025-09-15",
      updated: "2025-09-17",
    },
    {
      repo: "Banner-Claim",
      title: "Banner Claim",
      category: "minecraft",
      visibility: "private",
      description:
        "Claim land by placing a banner on a precious block, where copper through netherite sets the claim size. Includes protection, members and synced boundary rendering.",
      tags: ["Fabric"],
      created: "2025-08-05",
      updated: "2025-08-22",
    },
    {
      repo: "power-mod",
      title: "Power Mod",
      category: "minecraft",
      visibility: "private",
      description: "Fabric mod for Minecraft 1.21.1 built around investing experience into persistent powers.",
      tags: ["Fabric"],
      created: "2025-07-31",
      updated: "2025-08-15",
    },
    {
      repo: "adventures-new",
      title: "PSWG Addon: Adventures Ep 1",
      category: "minecraft",
      visibility: "private",
      description: "“Now this is podracing.” An add-on for Parzi's Star Wars Mod on Minecraft 1.20.2, published on CurseForge.",
      tags: ["Fabric", "PSWG"],
      links: [{ label: "CurseForge", url: "https://www.curseforge.com/minecraft/mc-mods/pswg-addon-episode-1" }],
      created: "2025-08-10",
      updated: "2025-08-10",
    },
    {
      repo: "swng",
      title: "SWNG",
      category: "minecraft",
      visibility: "private",
      description: "Early-stage Fabric mod for Minecraft 1.21.8, set up with data generation and client mixins.",
      tags: ["Fabric"],
      created: "2025-07-27",
      updated: "2025-07-27",
    },
    {
      repo: "vs-kingdoms",
      title: "VS Kingdoms",
      category: "minecraft",
      visibility: "private",
      description: "A kingdoms mod for Vintage Story that adds political systems and territorial management.",
      tags: ["Vintage Story", ".NET"],
      created: "2025-07-20",
      updated: "2025-07-20",
    },

    /* ---------- Game engines ---------- */
    {
      repo: "treps-game-engine",
      title: "Treps Engine",
      category: "engines",
      visibility: "private",
      featured: true,
      description:
        "Native C++20 foundation for 3D games, with an asset compiler, an editor, a command-line tool and its own test harness.",
      tags: ["CMake", "Editor tooling"],
      created: "2026-07-13",
      updated: "2026-07-14",
    },
    {
      repo: "frontier-guilds",
      title: "Frontier Guild",
      category: "engines",
      visibility: "public",
      description:
        "2D engine in Go on Ebitengine with an ECS, deterministic fixed-step physics, compressed save files and procedurally generated planets.",
      tags: ["Ebitengine", "ECS"],
      created: "2025-11-24",
      updated: "2026-01-18",
    },
    {
      repo: "rustic-engine",
      title: "Rustic Engine",
      category: "engines",
      visibility: "private",
      description:
        "Pure Rust 2D engine with zero dependencies: ECS, sprites and animation, tilemaps, A* pathfinding and AABB collision.",
      tags: ["ECS"],
      created: "2025-06-11",
      updated: "2025-06-23",
    },

    /* ---------- Games ---------- */
    {
      repo: "dagger_craft",
      title: "Crypt Rangers",
      category: "games",
      visibility: "private",
      featured: true,
      description:
        "Retro 2.5D open-world fantasy RPG with no engine underneath: C++20, SDL3 and a software raycaster, plus account-gated play, LAN hosting and dedicated servers.",
      tags: ["SDL3", "CMake", "Multiplayer"],
      links: [{ label: "Downloads", url: "https://github.com/Treppord/crypt-rangers-releases/releases" }],
      created: "2026-06-11",
      updated: "2026-07-03",
    },
    {
      repo: "sw-open-world",
      title: "SW Open World",
      category: "games",
      visibility: "private",
      description: "Star Wars open-world project built on OpenJK, the community-maintained Jedi Academy engine.",
      tags: ["OpenJK"],
      created: "2026-07-12",
      updated: "2026-07-12",
    },
    {
      repo: "StarforgeExpanse",
      title: "Starforge Expanse",
      category: "games",
      visibility: "private",
      description: "Game written in C, C++ and Objective-C++ on SDL3, with its own asset tooling and save system.",
      tags: ["SDL3", "CMake"],
      created: "2026-07-10",
      updated: "2026-07-10",
    },
    {
      repo: "new-republic-mmo",
      title: "New Republic MMO",
      category: "games",
      visibility: "private",
      description: "C++ MMO project with its own asset tooling.",
      tags: ["CMake", "Multiplayer"],
      created: "2026-07-09",
      updated: "2026-07-09",
    },
    {
      repo: "frw",
      title: "FRW",
      category: "games",
      visibility: "private",
      description:
        "First-person immersive sim in Godot 4.4, built on the COGITO framework: interaction, inventory, combat, quests and saves.",
      tags: ["Godot", "COGITO"],
      created: "2026-07-15",
      updated: "2026-08-08",
    },
    {
      repo: "warsaw_valley",
      title: "Warsaw Valley",
      category: "games",
      visibility: "private",
      description:
        "Client/server top-down farming and life-sim RPG set in modern-day Warsaw, split into core, server and client modules.",
      tags: ["Gradle", "Multiplayer"],
      created: "2026-06-11",
      updated: "2026-06-11",
    },
    {
      repo: "cozy-pot-land",
      title: "Cozy Pot Land",
      category: "games",
      visibility: "private",
      description: "Isometric voxel game in Go and SDL3 with a 32×32 grid world, Blockbench models, LAN multiplayer and world saves.",
      tags: ["SDL3", "Blockbench", "Multiplayer"],
      created: "2025-10-03",
      updated: "2025-10-05",
    },
    {
      repo: "pb-mon",
      title: "PB-Mon",
      category: "games",
      visibility: "private",
      description: "Gen 1–style Pokémon game in Go on Ebitengine: grid movement, wild encounters, types, moves and levelling.",
      tags: ["Ebitengine"],
      created: "2025-08-06",
      updated: "2025-08-13",
    },
    {
      repo: "hex-eng",
      title: "Hex Eng",
      category: "games",
      visibility: "private",
      description: "Hex-grid card strategy game in Go with factions, castles, AI opponents, a deck builder and a card editor.",
      tags: ["Ebitengine"],
      created: "2025-06-25",
      updated: "2025-07-28",
    },
    {
      repo: "hoomans",
      title: "Hoomans",
      category: "games",
      visibility: "private",
      description:
        "Retro 2D survival sim on a custom Python engine, where every NPC is driven by DNA-inspired CNA attributes.",
      tags: ["Pygame"],
      created: "2025-05-08",
      updated: "2025-06-03",
    },

    /* ---------- Apps ---------- */
    {
      repo: "Melobiu",
      title: "Melobiu",
      category: "apps",
      visibility: "private",
      featured: true,
      description:
        "International dating app with real profiles, mutual matches, realtime chat and language moments like pronunciation and the Name Game. Runs on the web and iOS.",
      tags: ["Next.js", "Supabase", "Capacitor", "Playwright"],
      links: [{ label: "Website", url: "https://www.melobiu.com" }],
      created: "2026-09-08",
      updated: "2026-09-15",
    },
    {
      repo: "tsa",
      title: "Bonded Downloader",
      category: "apps",
      visibility: "private",
      description:
        "Native SwiftUI macOS app that speeds up large downloads by fetching byte ranges over several network interfaces at once.",
      tags: ["SwiftUI", "macOS"],
      created: "2026-07-10",
      updated: "2026-07-10",
    },
    {
      repo: "ennovated",
      title: "Ennovated",
      category: "apps",
      visibility: "private",
      description: "Local macOS dashboard that pulls Claude, GitHub, Simplicate, Teams and Outlook into one place.",
      tags: ["Electron", "React", "Vite", "Tailwind CSS"],
      created: "2026-06-23",
      updated: "2026-06-23",
    },
    {
      repo: "Spot-Club",
      title: "Spot Club Command",
      category: "apps",
      visibility: "private",
      description:
        "One control room for several Spotify accounts: assign them to venues and control playback, playlists and queues together.",
      tags: ["Spotify API", "OAuth"],
      links: [{ label: "Website", url: "https://spot-club.vercel.app/" }],
      created: "2026-06-19",
      updated: "2026-06-19",
    },
    {
      repo: "third-eye-scope",
      title: "Third Eye Scope",
      category: "apps",
      visibility: "private",
      description:
        "Creative software for real-time visuals driven by hand gestures and body tracking, including 3D hand pose and depth-aware interaction.",
      tags: ["MediaPipe", "Computer vision"],
      created: "2026-06-04",
      updated: "2026-06-05",
    },
    {
      repo: "distrokid-app",
      title: "Sundrop",
      category: "apps",
      visibility: "private",
      description: "Native desktop dashboard for Spotify artist analytics and top tracks, built with Rust and egui.",
      tags: ["egui", "Spotify API"],
      created: "2025-06-16",
      updated: "2025-06-23",
    },
    {
      repo: "trep-chat-ai",
      title: "Trep Chat AI",
      category: "apps",
      visibility: "private",
      description:
        "VS Code extension for chatting with DeepSeek and OpenAI models, with file references, saved history and one-click code apply.",
      tags: ["VS Code API", "OpenAI", "DeepSeek"],
      created: "2025-01-28",
      updated: "2025-01-31",
    },

    /* ---------- Websites & web apps ---------- */
    {
      repo: "pokegradenl",
      title: "PokeGrade.nl",
      category: "web",
      visibility: "public",
      featured: true,
      description:
        "Website for a Dutch Pokémon card grading service, with services and pricing, a multi-step submission flow and order tracking.",
      tags: ["Next.js", "React", "Tailwind CSS"],
      links: [{ label: "Website", url: "https://www.pokegrade.nl/" }],
      created: "2025-09-05",
      updated: "2025-09-08",
    },
    {
      repo: "ennovate-simplicated",
      title: "Ennovate Simplicated",
      category: "web",
      visibility: "private",
      description: "Web app for Ennovate built on Next.js 16 and React 19.",
      tags: ["Next.js", "React"],
      created: "2026-06-15",
      updated: "2026-06-15",
    },
    {
      repo: "poke-site",
      title: "Poke Site",
      category: "web",
      visibility: "private",
      description: "Pokémon website for Ennovate, built with Vue.",
      tags: ["Vue"],
      created: "2026-05-05",
      updated: "2026-05-05",
    },
    {
      repo: "release-planner",
      title: "Release Planner",
      category: "web",
      visibility: "private",
      description:
        "Plan and coordinate music releases with your team, on a React front end with a Go API and Supabase auth and Postgres.",
      tags: ["React", "Supabase", "PostgreSQL"],
      links: [{ label: "Website", url: "https://release-planner-omega.vercel.app/" }],
      created: "2026-01-21",
      updated: "2026-02-09",
    },
    {
      repo: "hook-core",
      title: "Hook",
      category: "web",
      visibility: "private",
      description: "Job board and talent marketplace that connects companies with vetted B2B SaaS and fintech copywriters.",
      tags: ["Next.js", "Express", "Supabase"],
      created: "2025-11-13",
      updated: "2025-11-13",
    },
    {
      repo: "you-clo",
      title: "YouClo",
      category: "web",
      visibility: "private",
      description: "Mobile-first marketplace for buying and selling clothes, with a Go REST API, a React front end and Supabase.",
      tags: ["React", "Vite", "Supabase"],
      links: [{ label: "Website", url: "https://you-clo.vercel.app/" }],
      created: "2025-10-19",
      updated: "2025-10-29",
    },
    {
      repo: "game-site",
      title: "GameHub",
      category: "web",
      visibility: "private",
      description: "Indie game platform in Go where developers upload and host games, each release versioned in GitHub-backed storage.",
      tags: ["Vercel", "GitHub API"],
      links: [{ label: "Website", url: "https://game-site-gamma-one.vercel.app/" }],
      created: "2025-07-16",
      updated: "2025-07-22",
    },

    /* ---------- APIs & backend ---------- */
    {
      repo: "crypt-rangers-api",
      title: "Crypt Rangers API",
      category: "api",
      visibility: "private",
      description:
        "Auth API for Crypt Rangers: account login, refresh-token rotation and short-lived multiplayer join tokens that servers can verify offline via JWKS.",
      tags: ["Next.js", "Supabase", "JWT"],
      created: "2026-06-26",
      updated: "2026-07-02",
    },
    {
      repo: "adfa",
      title: "ADFA",
      category: "api",
      visibility: "private",
      description:
        "Backend foundation for an artist analytics platform: profiles, campaigns, caching and integration boundaries for Spotify, TikTok and Instagram.",
      tags: ["Node.js"],
      created: "2026-06-09",
      updated: "2026-06-09",
    },
    {
      repo: "pokegradenl-cards",
      title: "PokeGrade Card Database",
      category: "api",
      visibility: "private",
      description: "Central API for graded cards: CRUD, tamper-evident QR codes, population statistics, search and audit logging.",
      tags: ["Supabase", "REST"],
      created: "2025-09-06",
      updated: "2025-09-07",
    },
    {
      repo: "pokegradenl-lookup",
      title: "PokeGrade Label System",
      category: "api",
      visibility: "private",
      description: "Go service that renders PSA-style grading labels as 300 DPI PNG sheets, with Supabase storage and lookup by ID.",
      tags: ["Supabase"],
      created: "2025-09-06",
      updated: "2025-09-07",
    },
    {
      repo: "mc-modder",
      title: "MC Modder",
      category: "api",
      visibility: "private",
      description: "Go backend that publishes Minecraft mod releases to Modrinth, CurseForge, GitHub, GitLab and Discord from one place.",
      tags: ["REST", "Modrinth API", "CurseForge API"],
      created: "2025-08-03",
      updated: "2025-08-03",
    },
    {
      repo: "jet-pulumi-salesforce-pkg",
      title: "Pulumi for Salesforce MC",
      category: "api",
      visibility: "private",
      description:
        "Infrastructure as code for Salesforce Marketing Cloud: email and SMS templates and customer journeys, managed with Pulumi in Go.",
      tags: ["Pulumi", "Salesforce"],
      created: "2024-12-10",
      updated: "2024-12-12",
    },

    /* ---------- Tools & generators ---------- */
    {
      repo: "blockbench-gen",
      title: "Blockbench Gen",
      category: "tools",
      visibility: "private",
      description: "Turns natural-language prompts into correctly scaled, Minecraft-proportioned Blockbench models.",
      tags: ["Blockbench", "Codex"],
      created: "2026-03-31",
      updated: "2026-04-05",
    },
    {
      repo: "nbt-gen",
      title: "NBT Gen",
      category: "tools",
      visibility: "private",
      description: "Turns building prompts into JSON specs, then into gzip-compressed Minecraft structure templates (.nbt).",
      tags: ["NBT", "Codex"],
      created: "2026-03-30",
      updated: "2026-03-30",
    },
    {
      repo: "itch",
      title: "TempMail Codes",
      category: "tools",
      visibility: "private",
      description: "Go CLI and web UI that creates temporary inboxes and extracts verification codes from incoming mail.",
      tags: ["CLI", "MailSlurp"],
      created: "2025-07-29",
      updated: "2025-07-29",
    },

    /* ---------- AI research ---------- */
    {
      repo: "innovation",
      title: "BMO",
      category: "ai",
      visibility: "private",
      description: "Modular cognitive architecture in Rust for AGI research, with independent modules talking over an async event bus.",
      tags: ["Event bus"],
      created: "2025-11-05",
      updated: "2025-11-08",
    },
    {
      repo: "joan",
      title: "JOAN AI",
      category: "ai",
      visibility: "private",
      description: "Conversational AI built from scratch with a custom transformer, conversation and vector memory, and autonomous learning.",
      tags: ["Transformers"],
      created: "2025-05-22",
      updated: "2025-05-26",
    },
    {
      repo: "cna",
      title: "CNA Editor",
      category: "ai",
      visibility: "private",
      description:
        "Editor for CNA, a compact DNA-inspired binary format for NPC attributes, including generating child entities from two parents.",
      tags: ["Binary formats"],
      created: "2025-05-08",
      updated: "2025-05-08",
    },
  ];

  // Language split per repo, in percent, as reported by GitHub.
  const languages = {
    /* LANGUAGES */
  };

  for (const project of projects) project.languages = languages[project.repo] || {};

  const languageColors = {
    Java: "#e0923a",
    Kotlin: "#a97bff",
    Go: "#00add8",
    Rust: "#dea584",
    C: "#a8b9cc",
    "C++": "#f34b7d",
    "C#": "#3fb950",
    "Objective-C": "#438eff",
    "Objective-C++": "#6866fb",
    Swift: "#f05138",
    TypeScript: "#3178c6",
    JavaScript: "#f1e05a",
    HTML: "#e34c26",
    CSS: "#8e5bd6",
    SCSS: "#c6538c",
    Vue: "#41b883",
    Svelte: "#ff3e00",
    Python: "#4b8bbe",
    GDScript: "#478cbf",
    GLSL: "#5686a5",
    HLSL: "#aace60",
    Metal: "#8f14e9",
    PLpgSQL: "#4f8fd1",
    SQL: "#e38c00",
    TSQL: "#e38c00",
    mcfunction: "#e22837",
    Lua: "#4b6bfb",
    Zig: "#ec915c",
    Shell: "#89e051",
    Makefile: "#427819",
    CMake: "#da3434",
    Dockerfile: "#6b8fa3",
    Groovy: "#4298b8",
    EJS: "#a91e50",
    MDX: "#fcb32c",
  };

  return {
    user: "Treppord",
    // Started programming at 13, in Java, making Minecraft mods.
    codingSince: 2017,
    categories,
    projects,
    languages,
    languageColors,
    // Build and glue languages that shouldn't count toward the skills overview.
    stackIgnore: ["Makefile", "CMake", "Dockerfile", "Batchfile", "PowerShell", "Shell", "Procfile", "Nix", "Groovy", "Other"],
  };
})();
